language: python
python:
  - "3.8"
install:
  - "pip install codecov"
  - "pip install nibabel"
  - "pip install -r requirements.txt"
script:
  - "export PYTHONPATH=${PWD}:${PYTHONPATH}"
  - "nosetests --with-coverage --cover-package=bidsmanager -w ./TEST --exclude=test_dicomreader.py Tests"
  - "codecov"
